version: '3'

services:
  nginx:
    image: nginx:1.22-alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - .:/code

  php:
    build:
      context: .
      dockerfile: Dockerfile  # Spécifier votre Dockerfile personnalisé
    volumes:
      - .:/code
    depends_on:
      - mongodb  # Dépend du service MongoDB

  mongodb:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: orph
    volumes:
      - mongodb_data:/data/db


volumes:
  mongodb_data:
